class Animations {
    companion object {
        val wave = Flipbook("wave%", 0, 3, 10)
        val wave_th2 = Flipbook("wave%_th2", 0, 3, 10)
        val wave_th3 = Flipbook("wave%_th3", 0, 3, 10)
        val walk = Flipbook("walk%", 0, 3, 4)
        val swim = Flipbook("swim%", 0, 5, 6)
        val gun_walk = Flipbook("gun_walk%", 0, 5, 6)
        val gun_swim = Flipbook("gun_swim%", 0, 5, 6)
        val cannoneer_walk = Flipbook("cannoneer_walk%", 0, 3, 6)
        val cannoneer_swim = Flipbook("cannoneer_swim%", 0, 5, 6)
        val pirate_walk = Flipbook("pirate_walk%", 0, 5, 6)
        val pirate_swim = Flipbook("pirate_swim%", 0, 5, 6)
        val spider_animation = Flipbook("spider%", 0, 3, 4)
        val beetle_animation = Flipbook("beetle%", 0, 3, 4)
        val slime_animation = Flipbook("slime%", 0, 1, 15)
        val crab_animation = Flipbook("crab%", 0, 3, 4)
        val swordfish = Flipbook("swordfish%", 0, 1, 30)
        val shark = Flipbook("shark%", 0, 1, 30)
        val loch = Flipbook("swordfish%", 0, 1, 30) // (unfinished)
        val inwards_portal = Flipbook("portal%", 4, 0, 15)
        val outwards_portal = Flipbook("portal%", 0, 4, 15)
        val disabled_portal = Flipbook("disabled_portal%", 0, 16, 5)
        val smoke = Flipbook("smoke%", 0, 4, 1)
        val flame = Flipbook("flame%", 0, 1, 1)
        val hex = Flipbook("hex%", 0, 3, 1)
        val enabler = Flipbook("enabler%", 0, 1, 20)
        val slimesmoke = Flipbook("slimesmoke%", 0, 3, 1)
        val frog_animation = Flipbook("frog%", 0, 4, 15)
        val witch_fly = Flipbook("witch_fly%", 0, 3, 15)
        val witch_cast_fly = Flipbook("witch_cast_fly%", 0, 7, 15)
    }
}