import com.soywiz.klock.seconds
import com.soywiz.korge.*
import com.soywiz.korge.view.*
import com.soywiz.korim.color.Colors
import com.soywiz.korim.format.*
import com.soywiz.korio.file.std.*
import com.soywiz.klock.timesPerSecond
import com.soywiz.korau.sound.*
import com.soywiz.korim.bitmap.slice
import com.soywiz.korio.async.delay
import com.soywiz.korio.async.launch

suspend fun main() = Korge(
	title = "Summer Game Jam",
	bgcolor = Colors.BLACK,
	width = 1080,
	height = 720,
	virtualWidth = Globals.viewWidth,
	virtualHeight = Globals.viewHeight,
	clipBorders = true
) {
	solidRect(Globals.viewWidth, Globals.viewHeight, Colors.DIMGRAY)

	val image = image(resourcesVfs["splash.png"].readBitmap()) {
		scale(Globals.viewWidth / 384, Globals.viewHeight / 256)
		smoothing = false
	}

	val autoRenderer = AutoRenderer(stage)

	Globals.autoRenderer = autoRenderer
	Globals.input = views.input
	Globals.coroutineContext = coroutineContext

	// For some reason, the only way to get the music to loop,
	// is if we don't stream it. Oh well
	val music = resourcesVfs["adventure.mp3"].readSound()

	loadTextures(autoRenderer)
	Sounds.load(resourcesVfs)
	image.visible = false

	setup()
	music.playNoCancelForever()

	addFixedUpdater(60.timesPerSecond) {
		autoRenderer.clear()
		Globals.controls.testKeysDown()
		step()
		draw()
	}
}

suspend fun loadTextures(renderer: AutoRenderer) {
	renderer.register("ball", resourcesVfs["assets/ball.png"].readBitmap().slice())
	renderer.register("beetle0", resourcesVfs["assets/beetle0.png"].readBitmap().slice())
	renderer.register("beetle1", resourcesVfs["assets/beetle1.png"].readBitmap().slice())
	renderer.register("beetle2", resourcesVfs["assets/beetle2.png"].readBitmap().slice())
	renderer.register("beetle3", resourcesVfs["assets/beetle3.png"].readBitmap().slice())
	renderer.register("bridge0", resourcesVfs["assets/bridge0.png"].readBitmap().slice())
	renderer.register("bridge1", resourcesVfs["assets/bridge1.png"].readBitmap().slice())
	renderer.register("bullet", resourcesVfs["assets/bullet.png"].readBitmap().slice())
	renderer.register("bushl", resourcesVfs["assets/bushl.png"].readBitmap().slice())
	renderer.register("bushl_th2", resourcesVfs["assets/bushl_th2.png"].readBitmap().slice())
	renderer.register("bushr", resourcesVfs["assets/bushr.png"].readBitmap().slice())
	renderer.register("bushr_th2", resourcesVfs["assets/bushr_th2.png"].readBitmap().slice())
	renderer.register("cannon_idle", resourcesVfs["assets/cannon0.png"].readBitmap().slice())
	renderer.register("cannoneer_death", resourcesVfs["assets/cannoneer_death.png"].readBitmap().slice())
	renderer.register("cannoneer_idle", resourcesVfs["assets/cannoneer_idle.png"].readBitmap().slice())
	renderer.register("cannoneer_parachute", resourcesVfs["assets/cannoneer_parachute.png"].readBitmap().slice())
	renderer.register("cannoneer_swim0", resourcesVfs["assets/cannoneer_swim0.png"].readBitmap().slice())
	renderer.register("cannoneer_swim1", resourcesVfs["assets/cannoneer_swim1.png"].readBitmap().slice())
	renderer.register("cannoneer_swim2", resourcesVfs["assets/cannoneer_swim2.png"].readBitmap().slice())
	renderer.register("cannoneer_swim3", resourcesVfs["assets/cannoneer_swim3.png"].readBitmap().slice())
	renderer.register("cannoneer_swim4", resourcesVfs["assets/cannoneer_swim4.png"].readBitmap().slice())
	renderer.register("cannoneer_swim5", resourcesVfs["assets/cannoneer_swim5.png"].readBitmap().slice())
	renderer.register("cannoneer_walk0", resourcesVfs["assets/cannoneer_walk0.png"].readBitmap().slice())
	renderer.register("cannoneer_walk1", resourcesVfs["assets/cannoneer_walk1.png"].readBitmap().slice())
	renderer.register("cannoneer_walk2", resourcesVfs["assets/cannoneer_walk2.png"].readBitmap().slice())
	renderer.register("cannoneer_walk3", resourcesVfs["assets/cannoneer_walk3.png"].readBitmap().slice())
	renderer.register("cannon_power", resourcesVfs["assets/cannon_power.png"].readBitmap().slice())
	renderer.register("cannon_power", resourcesVfs["assets/cannon_power.png"].readBitmap().slice())
	renderer.register("crab0", resourcesVfs["assets/crab0.png"].readBitmap().slice())
	renderer.register("crab1", resourcesVfs["assets/crab1.png"].readBitmap().slice())
	renderer.register("crab2", resourcesVfs["assets/crab2.png"].readBitmap().slice())
	renderer.register("crab3", resourcesVfs["assets/crab3.png"].readBitmap().slice())
	renderer.register("death", resourcesVfs["assets/death.png"].readBitmap().slice())
	renderer.register("disabled_portal0", resourcesVfs["assets/disabled_portal0.png"].readBitmap().slice())
	renderer.register("disabled_portal1", resourcesVfs["assets/disabled_portal1.png"].readBitmap().slice())
	renderer.register("disabled_portal2", resourcesVfs["assets/disabled_portal2.png"].readBitmap().slice())
	renderer.register("disabled_portal3", resourcesVfs["assets/disabled_portal3.png"].readBitmap().slice())
	renderer.register("disabled_portal4", resourcesVfs["assets/disabled_portal4.png"].readBitmap().slice())
	renderer.register("disabled_portal5", resourcesVfs["assets/disabled_portal5.png"].readBitmap().slice())
	renderer.register("disabled_portal6", resourcesVfs["assets/disabled_portal6.png"].readBitmap().slice())
	renderer.register("disabled_portal7", resourcesVfs["assets/disabled_portal7.png"].readBitmap().slice())
	renderer.register("disabled_portal8", resourcesVfs["assets/disabled_portal8.png"].readBitmap().slice())
	renderer.register("disabled_portal9", resourcesVfs["assets/disabled_portal9.png"].readBitmap().slice())
	renderer.register("disabled_portal10", resourcesVfs["assets/disabled_portal10.png"].readBitmap().slice())
	renderer.register("disabled_portal11", resourcesVfs["assets/disabled_portal11.png"].readBitmap().slice())
	renderer.register("disabled_portal12", resourcesVfs["assets/disabled_portal12.png"].readBitmap().slice())
	renderer.register("disabled_portal13", resourcesVfs["assets/disabled_portal13.png"].readBitmap().slice())
	renderer.register("disabled_portal14", resourcesVfs["assets/disabled_portal14.png"].readBitmap().slice())
	renderer.register("disabled_portal15", resourcesVfs["assets/disabled_portal15.png"].readBitmap().slice())
	renderer.register("disabled_portal16", resourcesVfs["assets/disabled_portal16.png"].readBitmap().slice())
	renderer.register("doublejump", resourcesVfs["assets/doublejump.png"].readBitmap().slice())
	renderer.register("enabler0", resourcesVfs["assets/enabler0.png"].readBitmap().slice())
	renderer.register("enabler1", resourcesVfs["assets/enabler1.png"].readBitmap().slice())
	renderer.register("fence_a", resourcesVfs["assets/fencea.png"].readBitmap().slice())
	renderer.register("fence_b", resourcesVfs["assets/fenceb.png"].readBitmap().slice())
	renderer.register("flame0", resourcesVfs["assets/flame0.png"].readBitmap().slice())
	renderer.register("flame1", resourcesVfs["assets/flame1.png"].readBitmap().slice())
	renderer.register("flower_a", resourcesVfs["assets/flowera.png"].readBitmap().slice())
	renderer.register("flower_b", resourcesVfs["assets/flowerb.png"].readBitmap().slice())
	renderer.register("frog0", resourcesVfs["assets/frog0.png"].readBitmap().slice())
	renderer.register("frog1", resourcesVfs["assets/frog1.png"].readBitmap().slice())
	renderer.register("frog2", resourcesVfs["assets/frog2.png"].readBitmap().slice())
	renderer.register("frog3", resourcesVfs["assets/frog3.png"].readBitmap().slice())
	renderer.register("frog4", resourcesVfs["assets/frog4.png"].readBitmap().slice())
	renderer.register("grassa", resourcesVfs["assets/grassa.png"].readBitmap().slice())
	renderer.register("grassb", resourcesVfs["assets/grassb.png"].readBitmap().slice())
	renderer.register("grassc", resourcesVfs["assets/grassc.png"].readBitmap().slice())
	renderer.register("gun", resourcesVfs["assets/gun.png"].readBitmap().slice())
	renderer.register("gun_death", resourcesVfs["assets/gun_death.png"].readBitmap().slice())
	renderer.register("gun_idle", resourcesVfs["assets/gun_idle.png"].readBitmap().slice())
	renderer.register("gun_swim0", resourcesVfs["assets/gun_swim0.png"].readBitmap().slice())
	renderer.register("gun_swim1", resourcesVfs["assets/gun_swim1.png"].readBitmap().slice())
	renderer.register("gun_swim2", resourcesVfs["assets/gun_swim2.png"].readBitmap().slice())
	renderer.register("gun_swim3", resourcesVfs["assets/gun_swim3.png"].readBitmap().slice())
	renderer.register("gun_swim4", resourcesVfs["assets/gun_swim4.png"].readBitmap().slice())
	renderer.register("gun_swim5", resourcesVfs["assets/gun_swim5.png"].readBitmap().slice())
	renderer.register("gun_walk0", resourcesVfs["assets/gun_walk0.png"].readBitmap().slice())
	renderer.register("gun_walk1", resourcesVfs["assets/gun_walk1.png"].readBitmap().slice())
	renderer.register("gun_walk2", resourcesVfs["assets/gun_walk2.png"].readBitmap().slice())
	renderer.register("gun_walk3", resourcesVfs["assets/gun_walk3.png"].readBitmap().slice())
	renderer.register("gun_walk4", resourcesVfs["assets/gun_walk4.png"].readBitmap().slice())
	renderer.register("gun_walk5", resourcesVfs["assets/gun_walk5.png"].readBitmap().slice())
	renderer.register("hex0", resourcesVfs["assets/hex0.png"].readBitmap().slice())
	renderer.register("hex1", resourcesVfs["assets/hex1.png"].readBitmap().slice())
	renderer.register("hex2", resourcesVfs["assets/hex2.png"].readBitmap().slice())
	renderer.register("hex3", resourcesVfs["assets/hex3.png"].readBitmap().slice())
	renderer.register("idle", resourcesVfs["assets/idle.png"].readBitmap().slice())
	renderer.register("mushroom_a", resourcesVfs["assets/mushrooma.png"].readBitmap().slice())
	renderer.register("mushroom_b", resourcesVfs["assets/mushroomb.png"].readBitmap().slice())
	renderer.register("nook", resourcesVfs["assets/nook.png"].readBitmap().slice())
	renderer.register("parachute", resourcesVfs["assets/parachute.png"].readBitmap().slice())
	renderer.register("pirate", resourcesVfs["assets/pirate.png"].readBitmap().slice())
	renderer.register("pirate_claw", resourcesVfs["assets/pirate_claw.png"].readBitmap().slice())
	renderer.register("pirate_death", resourcesVfs["assets/pirate_death.png"].readBitmap().slice())
	renderer.register("pirate_idle", resourcesVfs["assets/pirate_idle.png"].readBitmap().slice())
	renderer.register("pirate_parachute", resourcesVfs["assets/pirate_parachute.png"].readBitmap().slice())
	renderer.register("pirate_shoot", resourcesVfs["assets/pirate_shoot.png"].readBitmap().slice())
	renderer.register("pirate_swim0", resourcesVfs["assets/pirate_swim0.png"].readBitmap().slice())
	renderer.register("pirate_swim1", resourcesVfs["assets/pirate_swim1.png"].readBitmap().slice())
	renderer.register("pirate_swim2", resourcesVfs["assets/pirate_swim2.png"].readBitmap().slice())
	renderer.register("pirate_swim3", resourcesVfs["assets/pirate_swim3.png"].readBitmap().slice())
	renderer.register("pirate_swim4", resourcesVfs["assets/pirate_swim4.png"].readBitmap().slice())
	renderer.register("pirate_swim5", resourcesVfs["assets/pirate_swim5.png"].readBitmap().slice())
	renderer.register("pirate_walk0", resourcesVfs["assets/pirate_walk0.png"].readBitmap().slice())
	renderer.register("pirate_walk1", resourcesVfs["assets/pirate_walk1.png"].readBitmap().slice())
	renderer.register("pirate_walk2", resourcesVfs["assets/pirate_walk2.png"].readBitmap().slice())
	renderer.register("pirate_walk3", resourcesVfs["assets/pirate_walk3.png"].readBitmap().slice())
	renderer.register("pirate_walk4", resourcesVfs["assets/pirate_walk4.png"].readBitmap().slice())
	renderer.register("pirate_walk5", resourcesVfs["assets/pirate_walk5.png"].readBitmap().slice())
	renderer.register("plant", resourcesVfs["assets/plant.png"].readBitmap().slice())
	renderer.register("platform_center", resourcesVfs["assets/platformc.png"].readBitmap().slice())
	renderer.register("platform_center_th2", resourcesVfs["assets/platformc_th2.png"].readBitmap().slice())
	renderer.register("platform_center_th3", resourcesVfs["assets/platformc_th3.png"].readBitmap().slice())
	renderer.register("platform_east", resourcesVfs["assets/platforme.png"].readBitmap().slice())
	renderer.register("platform_east_th2", resourcesVfs["assets/platforme_th2.png"].readBitmap().slice())
	renderer.register("platform_east_th3", resourcesVfs["assets/platforme_th3.png"].readBitmap().slice())
	renderer.register("platform_north", resourcesVfs["assets/platformn.png"].readBitmap().slice())
	renderer.register("platform_north_th2", resourcesVfs["assets/platformn_th2.png"].readBitmap().slice())
	renderer.register("platform_north_th3", resourcesVfs["assets/platformn_th3.png"].readBitmap().slice())
	renderer.register("platform_north_east", resourcesVfs["assets/platformne.png"].readBitmap().slice())
	renderer.register("platform_north_east_th2", resourcesVfs["assets/platformne_th2.png"].readBitmap().slice())
	renderer.register("platform_north_east_th3", resourcesVfs["assets/platformne_th3.png"].readBitmap().slice())
	renderer.register("platform_north_west", resourcesVfs["assets/platformnw.png"].readBitmap().slice())
	renderer.register("platform_north_west_th2", resourcesVfs["assets/platformnw_th2.png"].readBitmap().slice())
	renderer.register("platform_north_west_th3", resourcesVfs["assets/platformnw_th3.png"].readBitmap().slice())
	renderer.register("platform_south", resourcesVfs["assets/platforms.png"].readBitmap().slice())
	renderer.register("platform_south_th2", resourcesVfs["assets/platforms_th2.png"].readBitmap().slice())
	renderer.register("platform_south_th3", resourcesVfs["assets/platforms_th3.png"].readBitmap().slice())
	renderer.register("platform_south_east", resourcesVfs["assets/platformse.png"].readBitmap().slice())
	renderer.register("platform_south_east_th2", resourcesVfs["assets/platformse_th2.png"].readBitmap().slice())
	renderer.register("platform_south_east_th3", resourcesVfs["assets/platformse_th3.png"].readBitmap().slice())
	renderer.register("platform_south_west", resourcesVfs["assets/platformsw.png"].readBitmap().slice())
	renderer.register("platform_south_west_th2", resourcesVfs["assets/platformsw_th2.png"].readBitmap().slice())
	renderer.register("platform_south_west_th3", resourcesVfs["assets/platformsw_th3.png"].readBitmap().slice())
	renderer.register("platform_west", resourcesVfs["assets/platformw.png"].readBitmap().slice())
	renderer.register("platform_west_th2", resourcesVfs["assets/platformw_th2.png"].readBitmap().slice())
	renderer.register("platform_west_th3", resourcesVfs["assets/platformw_th3.png"].readBitmap().slice())
	renderer.register("portal0", resourcesVfs["assets/portal0.png"].readBitmap().slice())
	renderer.register("portal1", resourcesVfs["assets/portal1.png"].readBitmap().slice())
	renderer.register("portal2", resourcesVfs["assets/portal2.png"].readBitmap().slice())
	renderer.register("portal3", resourcesVfs["assets/portal3.png"].readBitmap().slice())
	renderer.register("portal4", resourcesVfs["assets/portal4.png"].readBitmap().slice())
	renderer.register("pressspace", resourcesVfs["assets/pressspace.png"].readBitmap().slice())
	renderer.register("rock_a", resourcesVfs["assets/rocka.png"].readBitmap().slice())
	renderer.register("rock_b", resourcesVfs["assets/rockb.png"].readBitmap().slice())
	renderer.register("shark0", resourcesVfs["assets/shark0.png"].readBitmap().slice())
	renderer.register("shark1", resourcesVfs["assets/shark1.png"].readBitmap().slice())
	renderer.register("sign", resourcesVfs["assets/sign.png"].readBitmap().slice())
	renderer.register("signboard", resourcesVfs["assets/signboard.png"].readBitmap().slice())
	renderer.register("sky", resourcesVfs["assets/sky.png"].readBitmap().slice())
	renderer.register("sky_th2", resourcesVfs["assets/sky_th2.png"].readBitmap().slice())
	renderer.register("slime0", resourcesVfs["assets/slime0.png"].readBitmap().slice())
	renderer.register("slime1", resourcesVfs["assets/slime1.png"].readBitmap().slice())
	renderer.register("slimesmoke0", resourcesVfs["assets/slimesmoke0.png"].readBitmap().slice())
	renderer.register("slimesmoke1", resourcesVfs["assets/slimesmoke1.png"].readBitmap().slice())
	renderer.register("slimesmoke2", resourcesVfs["assets/slimesmoke2.png"].readBitmap().slice())
	renderer.register("slimesmoke3", resourcesVfs["assets/slimesmoke3.png"].readBitmap().slice())
	renderer.register("slot", resourcesVfs["assets/slot.png"].readBitmap().slice())
	renderer.register("smoke0", resourcesVfs["assets/smoke0.png"].readBitmap().slice())
	renderer.register("smoke1", resourcesVfs["assets/smoke1.png"].readBitmap().slice())
	renderer.register("smoke2", resourcesVfs["assets/smoke2.png"].readBitmap().slice())
	renderer.register("smoke3", resourcesVfs["assets/smoke3.png"].readBitmap().slice())
	renderer.register("smoke4", resourcesVfs["assets/smoke4.png"].readBitmap().slice())
	renderer.register("spider0", resourcesVfs["assets/spider0.png"].readBitmap().slice())
	renderer.register("spider1", resourcesVfs["assets/spider1.png"].readBitmap().slice())
	renderer.register("spider2", resourcesVfs["assets/spider2.png"].readBitmap().slice())
	renderer.register("spider3", resourcesVfs["assets/spider3.png"].readBitmap().slice())
	renderer.register("star", resourcesVfs["assets/star.png"].readBitmap().slice())
	renderer.register("stump", resourcesVfs["assets/stump.png"].readBitmap().slice())
	renderer.register("swim0", resourcesVfs["assets/swim0.png"].readBitmap().slice())
	renderer.register("swim1", resourcesVfs["assets/swim1.png"].readBitmap().slice())
	renderer.register("swim2", resourcesVfs["assets/swim2.png"].readBitmap().slice())
	renderer.register("swim3", resourcesVfs["assets/swim3.png"].readBitmap().slice())
	renderer.register("swim4", resourcesVfs["assets/swim4.png"].readBitmap().slice())
	renderer.register("swim5", resourcesVfs["assets/swim5.png"].readBitmap().slice())
	renderer.register("swordfish0", resourcesVfs["assets/swordfish0.png"].readBitmap().slice())
	renderer.register("swordfish1", resourcesVfs["assets/swordfish1.png"].readBitmap().slice())
	renderer.register("title", resourcesVfs["assets/title.png"].readBitmap().slice())
	renderer.register("tree", resourcesVfs["assets/tree.png"].readBitmap().slice())
	renderer.register("tutorial", resourcesVfs["assets/tutorial.png"].readBitmap().slice())
	renderer.register("walk0", resourcesVfs["assets/walk0.png"].readBitmap().slice())
	renderer.register("walk1", resourcesVfs["assets/walk1.png"].readBitmap().slice())
	renderer.register("walk2", resourcesVfs["assets/walk2.png"].readBitmap().slice())
	renderer.register("walk3", resourcesVfs["assets/walk3.png"].readBitmap().slice())
	renderer.register("water", resourcesVfs["assets/water.png"].readBitmap().slice())
	renderer.register("water_th2", resourcesVfs["assets/water_th2.png"].readBitmap().slice())
	renderer.register("water_th3", resourcesVfs["assets/water_th3.png"].readBitmap().slice())
	renderer.register("wave0", resourcesVfs["assets/wave0.png"].readBitmap().slice())
	renderer.register("wave0_th2", resourcesVfs["assets/wave0_th2.png"].readBitmap().slice())
	renderer.register("wave0_th3", resourcesVfs["assets/wave0_th3.png"].readBitmap().slice())
	renderer.register("wave1", resourcesVfs["assets/wave1.png"].readBitmap().slice())
	renderer.register("wave1_th2", resourcesVfs["assets/wave1_th2.png"].readBitmap().slice())
	renderer.register("wave1_th3", resourcesVfs["assets/wave1_th3.png"].readBitmap().slice())
	renderer.register("wave2", resourcesVfs["assets/wave2.png"].readBitmap().slice())
	renderer.register("wave2_th2", resourcesVfs["assets/wave2_th2.png"].readBitmap().slice())
	renderer.register("wave2_th3", resourcesVfs["assets/wave2_th3.png"].readBitmap().slice())
	renderer.register("wave3", resourcesVfs["assets/wave3.png"].readBitmap().slice())
	renderer.register("wave3_th2", resourcesVfs["assets/wave3_th2.png"].readBitmap().slice())
	renderer.register("wave3_th3", resourcesVfs["assets/wave3_th3.png"].readBitmap().slice())
	renderer.register("win", resourcesVfs["assets/win.png"].readBitmap().slice())
	renderer.register("wing", resourcesVfs["assets/wing.png"].readBitmap().slice())
	renderer.register("witch_cast_fly0", resourcesVfs["assets/witch_cast_fly0.png"].readBitmap().slice())
	renderer.register("witch_cast_fly1", resourcesVfs["assets/witch_cast_fly1.png"].readBitmap().slice())
	renderer.register("witch_cast_fly2", resourcesVfs["assets/witch_cast_fly2.png"].readBitmap().slice())
	renderer.register("witch_cast_fly3", resourcesVfs["assets/witch_cast_fly3.png"].readBitmap().slice())
	renderer.register("witch_cast_fly4", resourcesVfs["assets/witch_cast_fly4.png"].readBitmap().slice())
	renderer.register("witch_cast_fly5", resourcesVfs["assets/witch_cast_fly5.png"].readBitmap().slice())
	renderer.register("witch_cast_fly6", resourcesVfs["assets/witch_cast_fly6.png"].readBitmap().slice())
	renderer.register("witch_cast_fly7", resourcesVfs["assets/witch_cast_fly7.png"].readBitmap().slice())
	renderer.register("witch_fly0", resourcesVfs["assets/witch_fly0.png"].readBitmap().slice())
	renderer.register("witch_fly1", resourcesVfs["assets/witch_fly1.png"].readBitmap().slice())
	renderer.register("witch_fly2", resourcesVfs["assets/witch_fly2.png"].readBitmap().slice())
	renderer.register("witch_fly3", resourcesVfs["assets/witch_fly3.png"].readBitmap().slice())
	renderer.registerFontCharacters(resourcesVfs["assets/font.png"].readBitmap())
}
